spring:
  application:
    name: ecommerce

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/roshni_creations}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:2200}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

server:
  port: 8080

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
